### ISSUE TITLE
Ignore just born mobs from count

### ISSUE THREAD

**Issue by LoneDev6** [NerdNu/MobLimiter#16]
Would be really nice to ignore just born mobs from the **chunk_max** counter as if I set chunk_max to 2 animals can't breed.

**Comment by redwallhp** [comment]
This functionality is by design. chunk_max is meant to be the highest amount ever possible to be in a chunk. It's a hard cap that prevents things like runaway spawners...or players intentionally breeding way too many mobs.

If you use the cull setting instead, MobLimiter will sweep over mobs and prune them down to the desired amount (e.g. 2) when the chunk unload. The chunk_max should definitely be higher than two.
